### ISSUE TITLE
Api design issue

### ISSUE THREAD

**Issue by CoreFloDev** [go-webauthn/webauthn#145]
### Version

0.8.2

### Description

Hi,

I don't understand why the user is required to `BeginLogin` and `BeginRegistration` to me in that situation, we don't have enough elements to know who the user is

### Reproduction

Look at `BeginLogin` and `BeginRegistration` functions

### Expectations

I would expect to be able to use BeginLogin and BeginRegistration without having to provide a user as what matters in that case is the challenge and RPID/RPOrigins for the credendial manager to be able to create the correct key.

Maybe it makes sense for registration as the user can provide personal information like email at this point of time. But for login, it forces the user to enter his email while he could only press a button and being logged in right away

**Comment by james-d-elliott** [comment]
The BeginDiscoverableLogin option can be used for discoverable logins. If this doesn't meet your needs please provide some documentation in a feature request as this is not a bug.
