### ISSUE TITLE
[API Consistency] There is no FinishDiscoverableLogin in Webauthn

### ISSUE THREAD

**Issue by boris-lenzinger** [go-webauthn/webauthn#172]
### Version

0.8.6

### Description

While using the code, I wanted to use the discoverable credentials feature. There is a BeginDiscoverableLogin method, a ValidateDiscoverableLogin method but no FinishDiscoverableLogin method.

I was wondering if there is a reason for this. I imagine that the code would be : 

```
// FinishDiscoverableLogin takes the response from the client and validate it against the user handler and stored session data.
func (webauthn *WebAuthn) FinishDiscoverableLogin(handler DiscoverableUserHandler, session SessionData, response *http.Request) (*Credential, error) {
	parsedResponse, err := protocol.ParseCredentialRequestResponse(response)
	if err != nil {
		return nil, err
	}

	return webauthn.ValidateDiscoverableLogin(handler, session, parsedResponse)
}
```

but I may miss something.

### Reproduction

This is related to the API and the available methods.

### Expectations

I would expect that a method FinishDiscoverableLogin would be available.

**Comment by james-d-elliott** [comment]
It was simply not considered really as the parsing is relatively low effort. We can just add it if there is desire for it.

**Comment by boris-lenzinger** [comment]
It would be more consistent. On the begin side, we have both BeginLogin and : 

```
// BeginDiscoverableLogin begins a client-side discoverable login, previously known as Resident Key logins.
func (webauthn *WebAuthn) BeginDiscoverableLogin(opts ...LoginOption) (*protocol.CredentialAssertion, *SessionData, error) {
	return webauthn.beginLogin(nil, nil, opts...)
}
```

and so I expected to have the same on the Finish side. Not a big deal if it is not added. As you said, the code is not that complicated to do. I let others vote on this if they feel there is a need for it.

**Comment by james-d-elliott** [comment]
I plan on just doing it since you want it, just not sure when I'll get around to it probably next weekend I'd guess, I'd welcome anyone else doing it too.

**Comment by boris-lenzinger** [comment]
> I plan on just doing it since you want it, just not sure when I'll get around to it probably next weekend I'd guess, I'd welcome anyone else doing it too.

I've created a pull request (https://github.com/go-webauthn/webauthn/pull/173) for this.
