### ISSUE TITLE
Implement AuthenticatorAttestationResponse interface

### ISSUE THREAD

**Issue by liuyangc3** [go-webauthn/webauthn#177]
### Description

Implement AuthenticatorAttestationResponse interface metheds:
- getAuthenticatorData()
- getPublicKey()
- getPublicKeyAlgorithm()

### Use Case

It's not easy to parse CBOR encoded data in some enviroments. It will be helpfull if implement
the methods described in spec, e.g:
> getPublicKey()
   This operation returns the DER [SubjectPublicKeyInfo](https://tools.ietf.org/html/rfc5280#section-4.1.2.7) of the new credential

### Documentation

https://www.w3.org/TR/webauthn-2/#authenticatorattestationresponse

**Comment by james-d-elliott** [comment]
> ### Use Case
> 
> It's not easy to parse CBOR encoded data in some enviroments. It will be helpfull if implement the methods described in spec, e.g:
> 
> > getPublicKey()
> > This operation returns the DER [SubjectPublicKeyInfo](https://tools.ietf.org/html/rfc5280#section-4.1.2.7) of the new credential

Why is it helpful? What is it going to be used for?

**Comment by liuyangc3** [comment]
> > ### Use Case
> > It's not easy to parse CBOR encoded data in some enviroments. It will be helpfull if implement the methods described in spec, e.g:
> > > getPublicKey()
> > > This operation returns the DER [SubjectPublicKeyInfo](https://tools.ietf.org/html/rfc5280#section-4.1.2.7) of the new credential
> 
> Why is it helpful? What is it going to be used for?

I guess this [link](https://www.w3.org/TR/webauthn-2/#sctn-public-key-easy) answers your question

**Comment by james-d-elliott** [comment]
Unfortunately it doesn't. This explains user agent / client-side convenience methods to avoid the RP having to parse the COSE format as far as I read it. This is not necessary for RP's that are already capable of parsing CBOR data.

Particularly telling lines are as follows:

>For those uses, user agents can do the work of parsing, expose the [authenticator data](https://www.w3.org/TR/webauthn-2/#authenticator-data) directly, and translate the [credential public key](https://www.w3.org/TR/webauthn-2/#credential-public-key) into a more convenient format.

> [Relying Parties](https://www.w3.org/TR/webauthn-2/#relying-party) that require this function to exist may not interoperate with older user-agents.

**Comment by liuyangc3** [comment]
Well, if user want to verify a sinature with the pulick key, first they need to parse public key from COSE format into PKIX, ASN.1 DER form, then pubkey probily encoded from DER to PEM format for DB or files etc presistence. If the user can get DER pubkey directly from a method of AuthenticatorAttestationResponse, that will be helpfull. and btw the spec also defined these helper method:
- getAuthenticatorData()
- getPublicKey()
- getPublicKeyAlgorithm()

But yes, user agents can do the work of parsing, just sometime developers are not farmilar with COSE DER etc such things.

**Comment by james-d-elliott** [comment]
The storage element is pretty unlikely to be a consideration. We expect the COSE encoded bytes to be stored and returned from storage.

What element of signature validation needs to be done manually by an implementer that isn't currently done automatically by the library?

**Comment by james-d-elliott** [comment]
Also maybe @nicksteele can weigh in on this one if he's not too busy.

**Comment by nicksteele** [comment]
I agree, additionally these operations could be performed on and returned from the client.
