### ISSUE TITLE
Library uses json.NewDecoder(body).Decode which might not error on trailing extra data

### ISSUE THREAD

**Issue by mitar** [go-webauthn/webauthn#189]
### Version

0.9.2

### Description

For example, in `ParseCredentialCreationResponseBody` you can see:

```go
	var ccr CredentialCreationResponse

	if err = json.NewDecoder(body).Decode(&ccr); err != nil {
		return nil, ErrBadRequest.WithDetails("Parse error for Registration").WithInfo(err.Error())
	}
```

`json.NewDecoder(r).Decode` by itself is meant as a streaming parser and it does not fail on its own if there is trailing data after payload. I use [such check](https://github.com/golang/go/issues/36225#issuecomment-1649618098) in my own code to mitigate that.

### Reproduction

N/A

### Documentation

See: https://github.com/golang/go/issues/36225

**Comment by james-d-elliott** [comment]
Yeah this seems fairly easy to add.

**Comment by mitar** [comment]
I think in general it would be useful to have also two defers:

```
defer body.Close()
defer io.Copy(io.Discard, body)
```

Just to make sure the body is drained and closed. (Improves connection reuse in Go http stack.)
