### ISSUE TITLE
Support Hints

### ISSUE THREAD

**Issue by jameshartig** [go-webauthn/webauthn#208]
### Description

`hints` is an array of strings that is on the opt-level of `PublicKeyCredentialCreationOptions`.

### Use Case

We'd like to use the new hints field to hint to the platform which kind of credentials we support.

### Documentation

See https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialcreationoptions-hints and https://www.w3.org/TR/webauthn-3/#enum-hints

**Comment by james-d-elliott** [comment]
I believe the linked PR satisfies the spec. I don't think anything more needs to be done other than including the values.

**Comment by jameshartig** [comment]
@james-d-elliott I agree and I appreciate the quick turnaround!
