### ISSUE TITLE
Add additional fields to AuthenticatorAttestationResponse

### ISSUE THREAD

**Issue by mitar** [go-webauthn/webauthn#221]
### Description

So `AuthenticatorAttestationResponse` struct contains only minimal fields which might be sent in JSON, but it looks the [spec allows additional fields](https://www.w3.org/TR/webauthn/#iface-authenticatorattestationresponse) (which are just extracted from `attestationOjbect`):

> To remove the need to parse CBOR at all in many cases, [getAuthenticatorData()](https://www.w3.org/TR/webauthn/#dom-authenticatorattestationresponse-getauthenticatordata) returns the [authenticator data](https://www.w3.org/TR/webauthn/#authenticator-data) from [attestationObject](https://www.w3.org/TR/webauthn/#dom-authenticatorattestationresponse-attestationobject). The [authenticator data](https://www.w3.org/TR/webauthn/#authenticator-data) contains other fields that are encoded in a binary format. However, helper functions are not provided to access them because [Relying Parties](https://www.w3.org/TR/webauthn/#relying-party) already need to extract those fields when [getting an assertion](https://www.w3.org/TR/webauthn/#sctn-getAssertion).

The issue I have is that I send `AuthenticatorAttestationResponse` over the wire in JSON from the client. And client adds those fields. But on the server I want to use JSON unmarshal with [`DisallowUnknownFields`](https://pkg.go.dev/encoding/json#Decoder.DisallowUnknownFields) set (primarily to detect changes in API I should check and possibly adapt to). And this is then currently not possible.

So I wonder if struct should define those additional optional fields, but not use them/ignore them?

**Comment by james-d-elliott** [comment]
We will add the specific fields mentioned, but will purposefully decline to officially support [DisallowUnknownFields](https://pkg.go.dev/encoding/json#Decoder.DisallowUnknownFields) due to the extensible and evolving nature of the specification itself.

**Comment by mitar** [comment]
Thanks, this looks great!
