### ISSUE TITLE
Windows Hello - Mismatch between ECCParameters in pubArea and credentialPublicKey

### ISSUE THREAD

**Issue by glacuesta-sa** [go-webauthn/webauthn#222]
### Version

0.9.4

### Description

Attestation bug with Direct & TPM on Windows Hello (Windows 11 22H2).
Searching found it was reported in another library too:
https://github.com/MasterKale/SimpleWebAuthn/issues/238

### Reproduction

Trying to enroll Windows 11 22H2 Hello authenticator with 
Attestation=Direct 
AuthenticatorType=Platform(TPM)

It ends in "Mismatch between ECCParameters in pubArea and credentialPublicKey" error but it should work.

### Expectations

Should enroll the device successfully.

**Comment by aseigler** [comment]
I could have sworn this got fixed (by me) in the summer/fall of 2022.  Are you saying you can reproduce this today on current codebase with W11 22H2?  Or is this 23H2?  Can you post a winver like this 
![image](https://github.com/go-webauthn/webauthn/assets/6605560/bd90edbe-26fd-44e2-8b32-a71959e023f2)

**Comment by glacuesta-sa** [comment]
@aseigler I'm sorry, I noticed this particular one has been using an older version. In which version was it fixed? Probably doesn't have the fix you're talking about.

**Comment by aseigler** [comment]
Whew, you had me there for a second.

Pretty sure this got fixed in #43 which is when the test for this particular case got added.

**Comment by aseigler** [comment]
Sounds good to me!  Thanks for the followup!
