### ISSUE TITLE
metadata: Make unmarshalMDSBLOB public/exported

### ISSUE THREAD

**Issue by iaburton** [go-webauthn/webauthn#247]
### Description

Hello!

I was looking at adding bits of the metadata package to my service for showing names & descriptions of registered authenticators (via aaguid). As far as I know the correct way for doing this is with the FIDO MDS service which is usable via the metadata package with the `ProductionMDSURL` const and the `PopulateMetadata` function.

However the options to the latter are few, it uses a hardcoded http.Client followed by a `io.Readall` (which is generally something I'd recommend against).

It looks like there is a private function that could be exposed to allow more uses cases, that function being [unmarshalMDSBLOB](https://github.com/go-webauthn/webauthn/blob/b6776911cac83b787955800d0c9ae9fc331ed6fe/metadata/metadata.go#L548) for use cases I've listed below.

PS: I don't mind submitting a MR for this as it's a relatively easy change. Or perhaps there is another reason this functionality wasn't already exposed in the metadata package? I searched existing/previous issues and didn't see anything on this.

Thank you!

### Use Case

1. For development, caching the blob locally instead of reading it remotely each time would save on network traffic.
2. The `ParseMetadata` function loads the data into a global variable in an unsafe way (mostly concurrency issues). Perhaps the client would like to parse/load some or all of the data into state stored elsewhere.
3. `unmarshalMDSBLOB` doesn't appear to use the http.Client it is being passed. Plus if it were exposed the blob could be retrieved using a custom http.Client or other method (before being passed to the unmarhal function).

**Comment by james-d-elliott** [comment]
Take a look at #239 which may satisfy some or all of this. We're reworking it to be more useful long term.

**Comment by iaburton** [comment]
Ah, you're correct, that looks like it would take care of this and then-some. Apologizes as I completely missed taking a look at the PRs before making this. Thanks for the info and quick reply.

**Comment by james-d-elliott** [comment]
No worries at all. I just didn't have time to confirm it matched all your needs until the weekend.

The general idea is to offload the elements that are just an implementation detail and give implementers the control over the domain logic since I can't account for every environment. With that design I think the implementer can accomplish everything they need to do to perform any form of decoding, caching, or locking they desire.

**Comment by james-d-elliott** [comment]
Nice, glad it's working well for you!
