### ISSUE TITLE
Methods should be designed to be flexible and not dictate or constrain the project’s API /Protocol definitions

### ISSUE THREAD

**Issue by igorrendulic** [go-webauthn/webauthn#248]
### Description

The problem is if you wan't to use another protocol to communicate with the server, method that require http.Request such as FinishRegistration makes it tedious to use the library. 

The issue is that if you include additional data in the same request (which is my current approach), the library cannot be used according to the documentation. 

### Use Case

- Sending custom data with the finish registration
- Using other protocol than http

### Documentation

```go
credential, err := webAuthn.FinishRegistration(user, session, r)
credential, err := webAuthn.FinishLogin(user, session, r)
```

**Comment by james-d-elliott** [comment]
All of the methods have an equivalent method that takes an io.Reader in the protocol package.

**Comment by igorrendulic** [comment]
Silly me. You're right. Sorry about that. It's clear in the documentation too.
