### ISSUE TITLE
metadata: Cached provider codepath may close file before attempting to truncate it

### ISSUE THREAD

**Issue by iaburton** [go-webauthn/webauthn#264]
### Version

0.11.0

### Description

Hello again,

As mentioned in #247 I've updated to v0.11 and had been using the latest changes to the metadata service with the provided cache provider. It was working well until today when the service was restarted, at which point it attempted to update the mds blob.

It kept failing with `truncate <file name>: file already closed`

I noticed [here](https://github.com/go-webauthn/webauthn/blob/f8b9177368828b5d276fb572af5e743f71c210be/metadata/providers/cached/provider.go#L84) that the decoder when passed the file is closing the file when it is finished. However just a few lines below, if the data is out of date and a file needs updating, then `doTruncateCopyAndSeekStart` is called which attempts to truncate the file that the decoder has already closed.

I tried passing the `WithForceUpdate` true option as a workaround but that fails with "invalid argument", I suspect this is because the file was [Opened](https://github.com/go-webauthn/webauthn/blob/f8b9177368828b5d276fb572af5e743f71c210be/metadata/providers/cached/util.go#L28) with READ only, and truncate is a write-level permission.

I think the suggested fix would be to not defer close the passed readcloser in the decoder (perhaps just pass it as a reader), and also open the file with `OpenFile` passing RW flags rather than just R flags. I can submit a PR if that helps.

### Reproduction

Open an outdated MDS blob with the cached provider, default settings should reproduce it. For reference here is my abridged constructor, I pass a NewFunc because I need to be able to configure `PermitZeroAAGUID` to the underlying memory provider

```
wconf.MDS, err = cached.New(
			cached.WithClient(common.CleanHTTP()),
			cached.WithPath(conf.MDSPath),
			cached.WithNew(providerFunc(conf.MDSPermitZeroAAGUID)),
		)

// providerFunc
func providerFunc(permitZeroAAGUID bool) cached.NewFunc {
	// This is the same as the default in webauthn/metadata/providers/cached
	// but with a configurable permit zero.
	return func(mds *metadata.Metadata) (metadata.Provider, error) {
		return memory.New(
			memory.WithMetadata(mds.ToMap()),
			memory.WithValidateEntry(true),
			memory.WithValidateEntryPermitZeroAAGUID(permitZeroAAGUID),
			memory.WithValidateTrustAnchor(true),
			memory.WithValidateStatus(true),
		)
	}
}
```

**Comment by james-d-elliott** [comment]
Thanks, pretty certain the fix is above.
