### ISSUE TITLE
Add support for fasthttp or decouple FinishRegistration from net/http

### ISSUE THREAD

**Issue by william-mens** [go-webauthn/webauthn#297]
### Description

This is a feature request to improve the flexibility of the WebAuthn library by decoupling the FinishRegistration method (and similar methods) from being tied to net/http. Currently, frameworks like Fiber, which are based on fasthttp, encounter compatibility issues because the library only supports *http.Request.

When using Fiber’s c.Request() (which returns a *fasthttp.Request), developers encounter a type mismatch error, forcing them to rely on adaptors (such as fasthttpadaptor) to convert between fasthttp.Request and *http.Request. While this workaround works, it adds unnecessary complexity and dependency bloat to the application.

Frameworks like Fiber are popular for their performance and low resource usage.
Adding native support for fasthttp or abstracting the HTTP request layer will remove the need for adaptors and keep applications lightweight. A more flexible API will broaden the potential use of the library across a wider range of Go web frameworks.

Proposed Solution:
- Consider decoupling the WebAuthn methods like FinishRegistration from being tightly bound to *http.Request.
- Implement an abstraction layer using interfaces that can support both net/http and fasthttp.
- Allow developers to pass custom request-handling logic, making the library more flexible across different frameworks.

Steps to Reproduce:
- Use the WebAuthn library in a Fiber-based application.
- Attempt to call FinishRegistration using c.Request() (Fiber's fasthttp.Request).
- Observe the type mismatch error: cannot use c.Request() (value of type *fasthttp.Request) as *http.Request.

Current Workaround:
To bypass the type incompatibility, developers must use an adaptor:
req, err := fasthttpadaptor.ConvertRequest(c.Context())
if err != nil {
    // Handle error
}
credential, err := webAuthn.FinishRegistration(authAuth, user, sessionData, req)

**Comment by james-d-elliott** [comment]
I'd welcome the docs change. Ideally at some stage I'll convert all docs into godoc but that's not necessary for now.

I'll look into the error later, do you know where the error is coming from using GDB?

Does the following func called on the error give more helpful error output?

```go
func formatWebAuthnError(err error) error {
	out := &protocol.Error{}

	if errors.As(err, &out) {
		if len(out.DevInfo) == 0 {
			return err
		}

		if len(out.Type) == 0 {
			return fmt.Errorf("%w: %s", err, out.DevInfo)
		}

		return fmt.Errorf("%w (%s): %s", err, out.Type, out.DevInfo)
	}

	return err
}
```

**Comment by william-mens** [comment]
Hello @james-d-elliott 
Sorry for the late reply, and thank you so much for your support and help with the WebAuthn integration! I managed to resolve the error – it was a small mistake on my end. Thanks to your guidance and the amazing library, we’ve successfully integrated WebAuthn and are already live.

I’ll also work on updating the docs
