### ISSUE TITLE
Remove the dependency of golang.org/x/crypto

### ISSUE THREAD

**Issue by bigradish** [go-webauthn/webauthn#320]
### Version

0.11.2

### Description

The use of golang.org/x/crypto is just for its ed25519 package, but it is just a copy of the one in Go's standard library. So you can use the standard library directly. This can reduce an unnecessary big package.
Thank you.

### Reproduction

The ed25519 package of golang.org/x/crypto is for verification.

**Comment by james-d-elliott** [comment]
It's used for OSCP as well.

**Comment by bigradish** [comment]
Thank you for your answer.
I searched the source code, and didn't find any use of the package golang.org/x/crypto except for its sub-package ed25519. Could you tell where it is used for OSCP?

________________________________
发件人: James Elliott ***@***.***>
发送时间: 2024年10月26日 12:40
收件人: go-webauthn/webauthn ***@***.***>
抄送: bigradish ***@***.***>; Author ***@***.***>
主题: Re: [go-webauthn/webauthn] Remove the dependency of golang.org/x/crypto (Issue #320)


It's used for OSCP as well.

―

**Comment by james-d-elliott** [comment]
No worries and of course: 

- https://github.com/go-webauthn/webauthn/blob/4ddacaac0c9d04c6b28186094b7c7b55a524271e/metadata/decode.go#L219-L227
- https://github.com/go-webauthn/x/blob/bdec438568bea71b3e113acbd26ddabc8857881c/revoke/revoke.go#L135-L158

**Comment by bigradish** [comment]
Thank you.
But github.com/go-webauthn/x is just another package which uses golang.org/x/crypto. For the package github.com/go-webauthn/webauthn itself, it can be independent on golang.org/x/crypto, though it depends indirectly.
I think it should be better to remove the dependency in github.com/go-webauthn/webauthn, for if github.com/go-webauthn/x removes the dependency in future, the whole project will also exclude the big package.

________________________________
发件人: James Elliott ***@***.***>
发送时间: 2024年10月27日 8:01
收件人: go-webauthn/webauthn ***@***.***>
抄送: bigradish ***@***.***>; Author ***@***.***>
主题: Re: [go-webauthn/webauthn] Remove the dependency of golang.org/x/crypto (Issue #320)


No worries and of course:

  *   https://github.com/go-webauthn/webauthn/blob/4ddacaac0c9d04c6b28186094b7c7b55a524271e/metadata/decode.go#L219-L227
  *   https://github.com/go-webauthn/x/blob/bdec438568bea71b3e113acbd26ddabc8857881c/revoke/revoke.go#L135-L158

―
