### ISSUE TITLE
After v0.10.2, backupEligible flag inconsistency detected during login validation

### ISSUE THREAD

**Issue by hiifong** [go-webauthn/webauthn#335]
### Version

0.11.2, 0.11.1, 0.11.0

### Description

as title
![image](https://github.com/user-attachments/assets/68d636f9-ee88-4465-affd-5150fe547699)

### Reproduction

build from [@go-gitea/gitea#713364fc718d1d53840bd83ba6f6c307bd213fa8
](https://github.com/go-gitea/gitea/tree/713364fc718d1d53840bd83ba6f6c307bd213fa8)

**Comment by james-d-elliott** [comment]
This occurs if the backup eligible flag has changed with bad authenticators or relying parties not storing the flag.
