### ISSUE TITLE
x509: trust chain validation fails when attestation certificate includes issuer URL

### ISSUE THREAD

**Issue by james-d-elliott** [go-webauthn/webauthn#342]
### Version

0.11.2, 0.11.1, 0.11.0

### Description

See:

- https://github.com/go-webauthn/webauthn/issues/275#issuecomment-2500932588
- https://github.com/go-webauthn/webauthn/issues/275#issuecomment-2504565325

### Reproduction

See above

**Comment by james-d-elliott** [comment]
@on-keyday  would you mind trying `github.com/go-webauthn/webauthn@65cb33878e3afbc1d6a5d4a31e3676b12c0f5717`? It should print all attested certificates, I suspect the intermediates are located within the attestation itself.

**Comment by on-keyday** [comment]
Yes you are right. I found the parent is bundled.
I realized that reporting and fixing each issue individually might not be the most efficient approach, so I decided to dive into the code and create a PR.
Adding the parent to verifier.Intermediates worked, but I encountered the next error
```
2024/12/05 02:41:10 Unable to validate attestation signature statement during attestation validation: invalid certificate chain from MDS: x509: certificate specifies an incompatible key usage
```
I found the UnknownExtKeyUsage of x5c has an OID 2.23.133.8.3, which matches tcgKpAIKCertificate in attestation_tpm.go:
https://oid-rep.orange-labs.fr/cgi-bin/display?oid=2.23.133.8.3&action=display
https://github.com/go-webauthn/webauthn/blob/5a5f13ccebbb7a066ec09af69c5455d946ed3606/protocol/attestation_tpm.go#L275
https://github.com/golang/go/blob/61232096579d8801cb3513c84a97c141d50ad242/src/crypto/x509/x509.go#L730
The parent certificate also has two OIDs in its UnknownExtKeyUsage

+ 2.23.133.8.3 (same as above)
+ 1.3.6.1.4.1.311.21.36 (a Microsoft-specific extension for Privacy CA encryption, defined in wincrypt.h as szOID_KP_PRIVACY_CA).

https://oid-rep.orange-labs.fr/cgi-bin/display?oid=1.3.6.1.4.1.311.21&a=display
https://abi-laboratory.pro/compatibility/Windows_8.1_to_Windows_10_1511_10586.494/x86_64/headers_diff/wintrust.dll/diff.html
```
// Enhanced Key Usage for Privacy CA encryption certificate
#define szOID_KP_PRIVACY_CA             "1.3.6.1.4.1.311.21.36"
```
To fix this, I wrote code to filter out these key usage extensions before verifying the certificates. With this change, the error no longer occurs.
I've submitted a PR addressing this issue. Please review and merge it if you don't mind.
