### ISSUE TITLE
Implement MDS3

### ISSUE THREAD

**Issue by james-d-elliott** [go-webauthn/webauthn#56]
The MDS2 is deprecated and we need to implement MDS3

**Comment by aseigler** [comment]
That would be prudent given that MDS2 is scheduled for shutdown at some point in the past or near future.

**Comment by james-d-elliott** [comment]
Yep I was just converting a project to an issue since you'd taken that up so you can close it ;)

**Comment by james-d-elliott** [comment]
Closed by 697bc4cb16d3cfc8755bd946b55b9699e76a4510
