### ISSUE TITLE
Allow multiple RPOrigins

### ISSUE THREAD

**Issue by FreddyDevelop** [go-webauthn/webauthn#76]
### Description

Allow multiple RPOrigins as suggested in https://github.com/duo-labs/webauthn/issues/143. 

Currently only one RPOrigin can be defined, which is sufficient for most use cases. But if you have a webpage and a mobile app (Android or/and iOS) and they should share the (passkeys) credentials you can't do this right now.

### Use Case

Share (passkeys) credentials between a mobile app and a webpage.

**Comment by james-d-elliott** [comment]
Thanks for posting the FR, I think this is a good idea. If no one else works on it I'll take a look at how other libraries do this more closely and figure out how to appropriately apply it.
