### ISSUE TITLE
Invalid link to maintainers group on security page.

### ISSUE THREAD

**Issue by tobiaszheller** [go-webauthn/webauthn#80]
### Version

0.3.1

### Description

All links into maintainers group on [security page](https://github.com/go-webauthn/webauthn/blob/master/SECURITY.md)  does not work (outside of go-webauthn org I suppose). 

### Reproduction

Check https://github.com/orgs/go-webauthn/teams/maintainers inside incognito mode in browser.

**Comment by james-d-elliott** [comment]
Thanks for reporting, will be aiming to figure out a solution to provide an email. For the time being there are  direct contact options on my profile and I'll update the link to use the people tab.

**Comment by james-d-elliott** [comment]
Interim fix by 6ec21f11d201912dd103d3de1ba6ec55d75c6d84

**Comment by james-d-elliott** [comment]
I've enabled the security advisory reporting beta as well.
