### ISSUE TITLE
Add AttestationConveyancePreference enterprise support

### ISSUE THREAD

**Issue by hochhaus** [go-webauthn/webauthn#90]
### Description

It would be nice if this library added support for enterprise attestation

### Use Case

For enterprise deployments (where all hardware and configurations and centrally maintained) it would be nice to be able to request enterprise attestation.

### Documentation

https://www.w3.org/TR/webauthn-2/#enum-attestation-convey

https://www.w3.org/TR/webauthn-2/#dom-attestationconveyancepreference-enterprise

https://groups.google.com/a/fidoalliance.org/g/fido-dev/c/TdCoQUsgFZU?pli=1

**Comment by james-d-elliott** [comment]
As far as I can tell the only implementation detail for RP's is the enum value "enterprise". If that's literally all then we can implement it relatively easily.

If there are some additional requirements or information in the attStmt we'd need to see those specific specs. If it's something that differs on browsers, devices, etc we'd need to have a way for the implementer to do specific validations.

**Comment by hochhaus** [comment]
Thanks @james-d-elliott.

> As far as I can tell the only implementation detail for RP's is the enum value "enterprise". If that's literally all then we can implement it relatively easil

As best I can tell at the moment, adding the enum value and treating it otherwise as `direct` is likely enough.

I'm still new to the spec though so I could be missing something.
