### ISSUE TITLE
Adding support for android devices

### ISSUE THREAD

**Issue by lisandromaselli** [go-webauthn/webauthn#92]
### Description

Android origin has the format of `android:apk-key-hash:${androidHash}` and for that reason is not a fullly qualified name. This case need to be handled outside the package?

### Documentation

https://github.com/google/webauthndemo/blob/main/src/libs/webauthn.ts

**Comment by FreddyDevelop** [comment]
Hi @james-d-elliott,
I think the problem is here:
https://github.com/go-webauthn/webauthn/blob/c2e06ed9dde45e70ea80cf9e7cdbd0e6a4cfd9fc/protocol/client.go#L91-L96

where the library formats the origin from the `CollectedClientData` as a fully qualified name. Which will not work for android, because android returns `android:apk-key-hash:${androidHash}` as origin and the format function then returns `android://`

Two possible solutions are:
1. remove the formatting
2. only format the origin when it does not start with `android`

**Comment by james-d-elliott** [comment]
Yeah you're right, I see. I will closely read relevant specs but it seems like this might be specifically the FIDO2 spec and is not part of the Webauthn spec at all. Which makes sense as it's not using Webauthn, it's a native API.

Webauthn itself requires this exact validation it seems, and the origin being formatted as a URL. As to how we solve it I'll have to closely look at the spec that governs it and it'll likely be similar to 2, but we'd use the full prefixes for those that exist (think there are two). I'm thinking it may also be wise to require this to be something that's explicitly enabled.

I would also be curious @nicksteele thinks if he has time to chime in (I would also like to remind him that there's a standing invitation to the org as a maintainer if he desires).

**Comment by aseigler** [comment]
I've seen this before: https://github.com/passwordless-lib/fido2-net-lib/pull/237

We ended up not formatting the origin if the origin had an unknown structure from [UriHostNameType](https://learn.microsoft.com/en-us/dotnet/api/system.urihostnametype).

**Comment by james-d-elliott** [comment]
Thanks a lot Alex I really appreciate the insight. I'm.assuming there were no additional considerations?

**Comment by lisandromaselli** [comment]
Thx!

**Comment by nicksteele** [comment]
Apologies for chiming in 4 months later. The multiple auth origin scheme is android-specific currently. As far as I know there's no plans to have hashes or multiple origin IDs for other response types. @james-d-elliott now that I'm back from my startup sabbatical I'm happy to help as a maintainer.

**Comment by james-d-elliott** [comment]
Great news. I'll invite you to the org then.
